version: '3.7'

networks:
  default:
    external: true
    name: ${NETWORK_NAME}
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: postgres -c shared_buffers=${POSTGRES_SHARED_BUFFER}
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
  pgbouncer:
    image: edoburu/pgbouncer
    container_name: ${PGBOUNCER_CONTAINER_NAME}
    restart: always
    environment:
       - DB_USER=${POSTGRES_USER}
       - DB_PASSWORD=${POSTGRES_PASSWORD}
       - DB_HOST=postgres
       - DB_NAME=${POSTGRES_DB}
       - POOL_MODE=transaction
       - MAX_CLIENT_CONN=200
       - DEFAULT_POOL_SIZE=50
       - RESERVE_POOL_SIZE=25
       - RESERVE_POOL_TIMEOUT=3
       - SERVER_LIFETIME=300
       - SERVER_IDLE_TIMEOUT=120
       - SERVER_CONNECT_TIMEOUT=5
       - SERVER_LOGIN_RETRY=3
       - QUERY_TIMEOUT=60
       - QUERY_WAIT_TIMEOUT=60
       - CLIENT_IDLE_TIMEOUT=60
       - CLIENT_LOGIN_TIMEOUT=60
    ports:
      - "127.0.0.1:${PGBOUNCER_PORT}:5432"
    depends_on:
      - postgres



volumes:
  postgres-data:
    driver: local
    # driver_opts:
    #   type: none
    #   device: ${POSTGRES_DB_PERSIST_PATH}
    #   o: bind
