version: '3.7'

networks:
  default:
    external: true
    name: ${NETWORK_NAME}
services:
  minio:
    container_name: ${MINIO_CONTAINER_NAME}
    restart: unless-stopped
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    ports:
      - "127.0.0.1:${MINIO_PORT}:9000"
      - "127.0.0.1:${MINIO_DASHBOARD_PORT}:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_REGION_NAME: ${MINIO_REGION_NAME}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
  minio-client:
    image: minio/mc:RELEASE.2023-07-21T20-44-27Z
    entrypoint: ["/bin/sh","-c"]
    depends_on:
      - minio
    command: 
      - |
        sleep 5
        mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
        mc mb --ignore-existing local/${MINIO_BUCKET}
        mc policy set download local/${MINIO_BUCKET}

volumes:
  minio-data:
    driver: local
    # driver_opts:
    #   type: none
    #   device: ${MINIO_PERSIST_PATH}
    #   o: bind
